### ISSUE TITLE
We should use `FlashStore` insteadof `FlashStoreSync`

### ISSUE THREAD

**Issue by huan** [wechaty/puppet-padlocal#102]
In our code, we are using `FlashStoreSync`:

https://github.com/padlocal/wechaty-puppet-padlocal/blob/a4b04b723fc4f75d08596a2952e08f4b5037983c/src/padlocal/cache-manager.ts#L7

the `FlashStoreSync` will provide a sync API with the cost of ... load all data in memory, which is not very efficient for memory usage.

I'd like to suggest that we should replace the `FlashStoreSync` with the `FlashStore` and using its async API. (with the latest version, with LevelDB backend).

## Best practice

The `wechaty-puppet-service` module can shows the best practice for using FlashStore:

https://github.com/wechaty/wechaty-puppet-service/blob/main/src/client/payload-store.ts

**Comment by padlocal** [comment]
Althougth `FlashStoreSync` has beed used in the code, BUT it is `FlashStore` indeed. Because `import FlashStoreSync from https://github.com/huan/flash-store;` will import `FlashStore` by default. I prefer it's a typo.

**Comment by huan** [comment]
Great to see that we continue fixing the ESM branch this week!

Yes, using a explicit import will be recommended (instead of using the `default` export):

```ts
import { FlashStore } from 'flash-store'
```
