### ISSUE TITLE
Autologin only works for one account and cannot be changed

### ISSUE THREAD

**Issue by vinceyyy** [wechaty/puppet-padlocal#107]
I have three WeChat accounts: A, B, and C. Only one of the them, account A can be auto logged in. 

After A logged in by scanning the QR code, it is autologin next time after kills the process or use `logout()`. However B and C cannot do that, they requires scanning the QR code every single time.

For example:
-> Run the process
-> Wechaty waiting for scan
-> scan with A, A logged in
-> kills the process (`ctrl + c`)
-> run the process
-> A auto logged in
-> A `logout()`
-> run the process
-> Wechaty waiting for scan
-> scan with B, B logged in
-> kills the process (`ctrl + c`)
-> run the process
-> Wechaty waiting for scan (B cannot auto login)

I contacted custom service on WeChat and was told that one token is bind to one account for autologin, but should be able to switch to another account.

**Comment by padlocal** [comment]
You can call `logout` to sign off current account.
