### ISSUE TITLE
Cannot connect to pad-local with WLAN 

### ISSUE THREAD

**Issue by BurgerBurglar** [wechaty/puppet-padlocal#111]
I cannot connect to pad-local when I'm connected to WiFi in my home. When I'm using the hotspot on my iPhone, it suddenly works. Obviously, I cannot use my hotspot all the time, so I would appreciate it if you can help with the debugging.

![34cc471e6a2e2f9e0823ad370d6f448](https://user-images.githubusercontent.com/33530007/136136079-60ca04ef-3aad-4ff4-bb68-2ab68d894407.png)

This is the error message that I've got.

I pinged `gateway.pad-local.com`, and it fails. It works when I'm using my phone. I'm in the US, using AT&T as my ISP, if that matters.

[Mirror issue](https://github.com/wechaty/wechaty.js.org/issues/1337)
```
node: 14.17.0
npm: 6.14.13
wechaty: 0.62.3
wechaty-puppet-padlocal: 0.4.2
OS: Windows 10
```

**Comment by padlocal** [comment]
It was caused by network issue.
