### ISSUE TITLE
Some deprecated functions need to be updated

### ISSUE THREAD

**Issue by 0kuang** [wechaty/puppet-padlocal#114]
https://github.com/padlocal/wechaty-puppet-padlocal/blob/a4b04b723fc4f75d08596a2952e08f4b5037983c/src/puppet-padlocal.ts#L145

StateSwitch on() is deprecated: use active() instead.

Similarly, replace `off()` with `inactivate()` .

**Comment by padlocal** [comment]
Fixed on branch `esm`, will be publisehd in version `1.x` soon,
