### ISSUE TITLE
获取企业微信发送的图片下载失败

### ISSUE THREAD

**Issue by JessicaChim** [wechaty/puppet-padlocal#119]
Error: [tid:1db8388a] [113ms] download file failed:{"host":{"host":"61.241.47.90","port":80},"payload":"qwAAAnpOIB6e7F8AAAAAAAAAAAAAAAACYQAAAAN2ZXIAAAABMQAAAAl3ZWl4aW5udW0AAAAKMTYwOTM0MjQ5NAAAAANzZXEAAAABMQAAAA1jbGllbnR2ZXJzaW9uAAAACTQwMjY1NDc1NAAAAAxjbGllbnRvc3R5cGUAAAAMaVBhZCBpT1MxNC4yAAAAB2F1dGhrZXkAAABCMEACAQEEOTA3AgEBAgEBAgRf7J4eAgM9FLoCAQACBEcqVCoCAz0R/gIEK+ZWcAIEbfUW0gIEYgXCMwIEPNBN4QQAAAAAB25ldHR5cGUAAAABMQAAAAxhY2NlcHRkdXBhY2sAAAABMQAAAAZyc2F2ZXIAAAABMQAAAAhyc2F2YWx1ZQAAAIAhUwvktvEEon5EKJuBoe+XjNpvIHh1pectmOJlgHpl8R9SaGu6SNIUuy38HkwhZMtf9ww5xF9qDK7ZkisQQ+ae43ih5Sx14Ux+sqlU93CqafVV3uUYE/qFuPjOoFKYsPnYn1OE6Lu4kKaVghtUhMGrQqTIVtj+sggS7bfJKJyDCwAAAAhmaWxldHlwZQAAAAEyAAAACnd4Y2hhdHR5cGUAAAABMAAAAAZmaWxlaWQAAAAAAAAAC2xhc3RyZXRjb2RlAAAAATAAAAAFaXBzZXEAAAABMAAAAA1jbGktcXVpYy1mbGFnAAAAATAAAAAJd3htc2dmbGFnAAAAAAAAAAt3eGF1dG9zdGFydAAAAAEwAAAADWRvd25waWNmb3JtYXQAAAABMQAAAAZvZmZzZXQAAAABMAAAAAtsYXJnZXN2aWRlbwAAAAEwAAAACnNvdXJjZWZsYWcAAAABMA==","unpackaeskey":"EodeWpdIQneSqUuoRAicsw=="}, retcode: -5103166

**Comment by padlocal** [comment]
-5103166 maybe means that the file is not valid.
