### ISSUE TITLE
客服无法联系

### ISSUE THREAD

**Issue by juneyang** [wechaty/puppet-padlocal#121]
*添加 PadLocal 技术支持咨询。http://pad-local.com/#/contactus*

客服无法联系成功，是已经不运营了吗？

**Comment by 9cat** [comment]
same here.   how to contact with the project lead, we want to continue to use it.

**Comment by 15628920786** [comment]
客服怎么联系，我们也想继续使用

**Comment by padlocal** [comment]
客服的账号有点问题，可以临时加 vagase 处理问题
