### ISSUE TITLE
Return data does not match when using same params to call a same api

### ISSUE THREAD

**Issue by willin** [wechaty/puppet-padlocal#126]
> 接口返回值有的时候不一致。 以 room.memberAll() 为例，昨天测试的时候还能拿出昵称之类的数据，今天晚上测就没有 payload

For example, `room.memberall()` sometimes returns contact[] data with payload but sometimes not.

```ts
import { log, Wechaty } from 'wechaty';

// just for test
export default async function ready(this: Wechaty): Promise<void> {
  const room = this.Room.load('19115444039@chatroom');
  const memberList = await room.memberAll();
  const text = memberList.map(
    (contact) => `昵称：${contact.name()}, id： ${contact.id}`
  );
  await room.say(text.join('\n')); // sometimes contact.name() --> null
  log.info('ready', JSON.stringify(memberList, null, 2));
}
```

--- 
Errored data:

```js
[
  {
    "_events": {},
    "_eventsCount": 0,
    "id": "zlove0123"
  },
  {
    "_events": {},
    "_eventsCount": 0,
    "id": "wxid_xvi7ycjvuogj22"
  },
  {
    "_events": {},
    "_eventsCount": 0,
    "id": "wxid_ibm3h1d26qr521"
  },
  {
    "_events": {},
    "_eventsCount": 0,
    "id": "wxid_bsyk3rnubtyt22"
  },
  {
    "_events": {},
    "_eventsCount": 0,
    "id": "wxid_i4bj51c56exu21"
  },
  {
    "_events": {},
    "_eventsCount": 0,
    "id": "qq985571093"
  },
  {
    "_events": {},
    "_eventsCount": 0,
    "id": "willinx"
  }
]
```

**Comment by huan** [comment]
`load()` is not a public API and should be avoided to be used.

use `find()` instead.

**Comment by willin** [comment]
when i change it into find: 

```ts
const room = (await this.Room.find('19115444039@chatroom')) as Room;
const memberList = await room.memberAll();
```

```
TypeError: Cannot read properties of null (reading 'memberAll')
```

**Comment by willin** [comment]
should be:

```ts
  const room = (await this.Room.find({ id: '19115444039@chatroom' })) as Room;
```

**Comment by willin** [comment]
emmm but i don't think it's something about it.

from my opinion of view, either got everytime, or never got.

**Comment by huan** [comment]
Yes, should be `{ id }`.

And you should NOT use `as Room` because that's not correct.

You need to check the return value to make sure it has been found or not.

The `find` highly depends on the puppet implementation to return the result to you, and you need to check it by yourself.

For example, consider you are using a new WeChat app on your phone: after you logged in to your WeChat account, you can not find all your rooms: it need some time to load up.

**Comment by huan** [comment]
> from my opinion of view, either got every time or never.

When we are in a highly dynamic, distributed, RPA-ed black-box world, that will not always be true.
