### ISSUE TITLE
Strange Contact data

### ISSUE THREAD

**Issue by willin** [wechaty/puppet-padlocal#127]
> 有一个非常特殊的数据。一般 id 就是微信号，weixin 字段是空的。如果没有加好友payload id 就是 wxix_xxxx或者 xxxx@stranger。但这一条特殊数据 weixin 字段里塞了东西

```ts
Friendship.search({
    weixin: 'someweixin' 
});
```

the unique data with payload.weixin: 

```js
{
  "_events": {},
  "_eventsCount": 0,
  "id": "$search$-someweixin",
  "payload": {
    "id": "qq000000", // masked
    "gender": 1,
    "type": 1,
    "name": "xxxxx",
    "avatar": "xxxxxxx",
    "alias": "",
    "weixin": "someweixin", // masked
    "city": "East",
    "friend": true,
    "province": "Beijing",
    "signature": "",
    "phone": []
  }
}
```

other contact[] data `weixin` is `""` and id is wechat account.

i have no idea why...

**Comment by padlocal** [comment]
If the contact you search is already your friend, you may get `weixin` field with value.
