### ISSUE TITLE
Is there a plan to support latest wechaty version?

### ISSUE THREAD

**Issue by willin** [wechaty/puppet-padlocal#129]
I've tried almost every versions of wechaty.

puppet-padlocal can only support `<=0.75.27`

Is there a plan to support latest wechaty version?

**Comment by willin** [comment]
#125

**Comment by huan** [comment]
Yes, you have linked to the answer: v1.x will be supported after

- #125 

has been merged.

So stay tuned!

**Comment by padlocal** [comment]
DONE
