### ISSUE TITLE
Question: how to get a real unique id of a contact

### ISSUE THREAD

**Issue by willin** [wechaty/puppet-padlocal#130]
> 我整理了一下 Contact id 在使用中已经发现的几种不同情况。大部分是微信号，未添加好友的是 wxid_xxxx 规则的字符串（这个类似于 hash 的字符串会不会变化？）。如果我想获得某个人的真正唯一的 id，或者统一的 wxid_xxxx 格式的数据的话，是否能够拿到？

Some I collected:

- Contact 
  - `$search$-weixin`
  - `$search$-13212341234`
  - `weixin` / `wxid_xxxx`
- Contact Protected Payload 
  - `$search$-` And  not a friend:  `v3_xxxxx@stranger`
  - `weixin` / `wxid_xxxx`
  - No idea: id `qq00000` and wechat `wechat`

Is there a way to get a real unique id like `wxid_xxxxx`? 

And I wonder whether `wxid_xxxx` hash of a contact will chagne?

**Comment by padlocal** [comment]
weixin / wxid_xxxx is the real id, `$search$` pattern is only used for internal usage.
