### ISSUE TITLE
About locally cached data

### ISSUE THREAD

**Issue by yzh1255245824** [wechaty/puppet-padlocal#138]
I know that `padlocal` will cache some data locally, so data loss will occur after switching devices such as uploading from the development environment to the production environment. Like this:
```javascript
// You try to find a contact by alias
const contact = bot.Contact.find({alias: xxx});

// Then you will find that the "contact" is empty, because there is no contact with the alias XXX...
// Although you did set the `alias` to XXX for this contact
```

But where are these data stored? If I copy them to other computers as they are, will it still cause data loss?

I remember you said in the last meeting that `MongoDB` can be used to solve this problem, but what data should I store in it?

**Comment by yzh1255245824** [comment]
And I found that there is a folder called `.wechaty` in the root directory of the computer. Is this where the local data is stored?

**Comment by padlocal** [comment]
Yeah，for contact you can use https://github.com/wechaty/puppet-padlocal/blob/6eef8d8d2a8487ec719ba3181ff5c36c13e45293/src/puppet-padlocal.ts#L1258 to sync all contacts as a workaround, but use it wisely.

**Comment by RunningCoderLee** [comment]
请问有没有单独更新某个联系人的方法，另外我看这个好像属于底层 API，我在 wechay 里怎么使用这个 api 呢 @padlocal
