### ISSUE TITLE
PuppetPadlocal  ts项目启动报错timestamp ??= 0;

### ISSUE THREAD

**Issue by NightRannie** [wechaty/puppet-padlocal#145]
今天搭建一个ts项目时，初始运行就报了这个错误
![bug](https://user-images.githubusercontent.com/50985610/156279632-5972383d-4b9a-43e8-a3d5-fe45dceaddbb.png)

运行环境
node :v14.5.0
wechaty: "^1.10.4",
wechaty-puppet-padlocal: "^0.4.2"
typescript:6.14.5

ts.config.json 为init默认设置

是否要配置什么
![bug](https://user-images.githubusercontent.com/50985610/156280793-f2e1c6a3-3bd6-4970-ba73-6fbc1bb4a5ee.png)

**Comment by suntong** [comment]
Have you ever made padlocal worked before? 

If not, you'll have better chance get it working if starting from here --
https://github.com/padlocal/wechaty-puppet-padlocal-demo/issues/13

Took me quite an effort to get the versions that works. YMMV.

**Comment by NightRannie** [comment]
it is okay,thank you

**Comment by simple890921** [comment]
应该吧 node 16+ 可以
