### ISSUE TITLE
wiki: how to get plain text from 笔记

### ISSUE THREAD

**Issue by suntong** [wechaty/puppet-padlocal#147]
1. Test the message content with `<type>24<\/type>`
2. If match, call the following function, to get plain text from 笔记:

```js
function WxNoteMsgFilter(content) {
  return '[笔记]\n'+ he.decode(he.decode(content.replace(/.*?<type>24<\/type>.*?<recorditem>(?:&lt;recordinfo&gt;|<!\[CDATA\[<recordinfo>).*?(?:&gt;&lt;datadesc&gt;|<datadesc>)(.*?)(<|&lt;)\/datadesc(>|&gt;).*?<\/recorditem>.*/s,'$1')))
}
```

Let me know if it works for you.

**Comment by padlocal** [comment]
Thanks for your wiki, I have moved the content to : https://github.com/wechaty/puppet-padlocal/wiki/Message-payload-parsers-list
