### ISSUE TITLE
新建群时如果成员列表里含有一个单方面把你删除的好友，则收不到room-invite事件

### ISSUE THREAD

**Issue by iyjian** [wechaty/puppet-padlocal#154]
新建群时如果成员列表里含有一个单方面把你删除的好友，则收不到room-invite事件

且之后的群事件都收不到。

**Comment by padlocal** [comment]
实际上应该是建群的时候 room-join 不会触发

**Comment by padlocal** [comment]
如果对方单方面把你删除了，提示需要添加好友，所有对方没有办法收到 `room-invite` 事件。
