### ISSUE TITLE
message.ID() && rpc error

### ISSUE THREAD

**Issue by Ran-Xing** [wechaty/puppet-padlocal#157]
今天遇见一个bug，挺奇怪的
## rpc error
1. 处理一条消息的时候
2. 正常返回 message.Say("xxxxxxxx")
3. 消息已经收到了，但是报了一个 Error
4. `rpc error: code = Internal desc = neither toId nor roomId`
5. 我和go的作者折腾了半天，发现是rpc的问题，希望有空排查下，如果需要，也可以远程 Debug

## message.ID()
onMessage 时间中，我使用 message.ID() 作为 key ，value 为 false
然后 fatal 了，试过 map.synp 线程锁，失败
后来 使用 message.From().ID() 成功避免这个问题

## 总结：
Docker 0.68 无以上问题
Docker 0.78 有这两个问题

**Comment by whale1st** [comment]
我今天也遇到这个问题了，同 Docker 0.78，在 使用 `msgId, err := msg.Say("ok") `时，会出现` rpc error: code = Internal desc = neither toId nor roomId`，而直接 `msg.Say("ok") `不去获取msgId时就不会出现这个错误信息。

**Comment by Ran-Xing** [comment]
@whale1st good 兄弟，欢迎常来play
