### ISSUE TITLE
[BUG]无法发送小程序卡片 code = Internal desc = Unexpected end of JSON input

### ISSUE THREAD

**Issue by whale1st** [wechaty/puppet-padlocal#160]
Docker image: wechaty/wechaty:0.56

Client: go-wechaty v0.4.0

发送小程序卡片时报错：
`2022/04/29 12:33:24 PuppetService onGrpcStreamEvent({type:EVENT_TYPE_SCAN payload:{"status":4}})
2022/04/29 12:33:24 qrcode: 
2022/04/29 12:33:25 PuppetService onGrpcStreamEvent({type:EVENT_TYPE_LOGIN payload:{"contactId":"wxid_zcqg40b2u812s7"}})
2022/04/29 12:33:25 PuppetService ContactRawPayload(wxid_zcqg40b2u812s7)
2022/04/29 12:33:25 用户【无空】登录成功
2022/04/29 12:33:26 PuppetService onGrpcStreamEvent({type:EVENT_TYPE_MESSAGE payload:{"messageId":"7107621927853647690"}})
2022/04/29 12:33:26 PuppetService MessagePayload(7107621927853647690)
2022/04/29 12:33:26 PuppetService ContactRawPayload(weixin)
2022/04/29 12:33:26 Message#MessageTypeRecalled[🗣Contact<微信团队>]
2022/04/29 12:33:26 PuppetService onGrpcStreamEvent({type:EVENT_TYPE_READY payload:{"data":"ready"}})
2022/04/29 12:33:29 PuppetService onGrpcStreamEvent({type:EVENT_TYPE_MESSAGE payload:{"messageId":"229651181245766025"}})
2022/04/29 12:33:29 PuppetService MessagePayload(229651181245766025)
2022/04/29 12:33:29 Message#MessageTypeUnknown[🗣Contact<无空>]        <msg>
<op id='11'>
<name>HandOffMaster</name>
<arg><handofflist opcode
2022/04/29 12:33:30 PuppetService onGrpcStreamEvent({type:EVENT_TYPE_READY payload:{"data":"ready"}})
2022/04/29 12:33:32 PuppetService onGrpcStreamEvent({type:EVENT_TYPE_MESSAGE payload:{"messageId":"1572393231145429601"}})
2022/04/29 12:33:32 PuppetService MessagePayload(1572393231145429601)
2022/04/29 12:33:32 Message#MessageTypeRecalled[🗣Contact<微信团队>]
2022/04/29 12:33:40 PuppetService RoomList()
2022/04/29 12:33:40 PuppetService RoomRawPayload(25047750333@chatroom)
2022/04/29 12:33:40 PuppetService RoomMemberList(25047750333@chatroom)
2022/04/29 12:33:40 PuppetService MessageSendMiniProgram(25047750333@chatroom,&schemas.MiniProgramPayload{Appid:"wx23dde3ba32269caa", Description:"肯德基+", PagePath:"pages/home/home.html", ThumbUrl:"http://img1.lukou.com/static/coupon/channel_app/template/1566471867138.png", Title:"肯德基自助点餐", Username:"gh_c22a7683f404@app", ThumbKey:"", ShareId:"", IconUrl:"http://mmbiz.qpic.cn/mmbiz_png/SE9ICmPPKWiaibdENZqwnjeIWiblOvnX4QFZMr2PJ704lOyphLBicqjwYbt9Rsiak2mYM8UBtTX91XgMg3lqs98DMMA/640?wx_fmt=png&wxfrom=200"})
rpc error: code = Internal desc = Unexpected end of JSON input`

**Comment by dchaofei** [comment]
你试下 0.78 版本的 wechaty 镜像

**Comment by whale1st** [comment]
> 你试下0.78版本的微信镜像

非常感谢，0.78版本的镜像可以正常发送小程序卡片。
