### ISSUE TITLE
Hard to present Emoticon message with FileBox

### ISSUE THREAD

**Issue by padlocal** [wechaty/puppet-padlocal#161]
### Description 

While implementing Padlocal to handle `Emoticon` messages, it's difficult to present `Emoticon` type message with `FileBox`, including BOTH receiving and sending messages.

#### Message -> FileBox

While constructing `FileBox` from receiving messages, we did this with some tricks before:
```
const emotionPayload = await emotionPayloadParser(messagePayload);
const emoticonBox = FileBox.fromUrl(emotionPayload.cdnurl, `message-${messageId}-emotion.jpg`);

emoticonBox.metadata = emotionPayload;
emoticonBox.mimeType = "emoticon";
```
The `messagePayload` is a xml text with following fields:
```
export interface EmojiMessagePayload {
  type: number;
  len: number;
  md5: string;
  cdnurl: string;
  width: number;
  height: number;
  gameext?: string;
}
```
It was embarrassing that, we had to put the core message payload into `metadata` and set `mimeType` explicitly. Now, `mimeType` has became deprecated in new version of `FileBox`, replaced by `mediaType` which is a readonly property. So the folloing code becomes anti-pattern.

https://github.com/wechaty/puppet-padlocal/blob/ce777495eb232eb254b6eb5cd050cf5dca0c3a43/src/puppet-padlocal.ts#L660

#### FileBox -> Message
While sending `Emoticon` messages with `FileBox`, we have to do the same:
```
const emoticonBox = FileBox.fromUrl("http://emoji.qpic.cn/wx_emoji/.../", `message-emotion.jpg`);

emoticonBox.mimeType = "emoticon";
emoticonBox.metadata = {
  md5: "45229f68c17167f57ba9393004fcef98",
  len: 12345,
  type: 2,
  gameext: "",
};

await toContact.say(emoticonBox)
```
### CALL FOR HELP
We need a more proper way to handle this situation, for both puppet developers and Wechaty users.

@huan Do you have any ideas?

**Comment by huan** [comment]
## Message -> FileBox

According to the below code

```ts
const emoticonBox = FileBox.fromUrl(emotionPayload.cdnurl, `message-${messageId}-emotion.jpg`);
```

Then the `mediaType` should be `image/jpeg` because the filename is `message-${messageId}-emotion.jpg`

## FileBox -> Message

According to the below code

```ts
const emoticonBox = FileBox.fromUrl("http://emoji.qpic.cn/wx_emoji/.../", `message-emotion.jpg`);
```

Then I believe the `mediaType` will be `image/jpeg` too.

**Comment by padlocal** [comment]
That's correct. But if you send the `FileBox` with `mediaType` as `image/jpeg`, then the emoticon message will be sent as normal image mesage.

**Comment by huan** [comment]
Yes, I remembered that. Our Wechaty API does not distinguish the Image and the Emoticon so we need a way to identify the emoticon of the images.

So it seems that we can only focus on the **sending** part of the API? Because when we have received an emoticon, we can just get a normal FileBox with the `image/jpeg` for that's the correct value.

When we are trying to **send** an emoticon, we need a way to differentiate it with the Image.

**Comment by padlocal** [comment]
ok, I have put the payload into meta, and judge emoticon message by entire metadata

**Comment by huan** [comment]
> ok, I have put the payload into meta, and judge emoticon message by entire metadata

I feel if there has any MIME type that we can use for our emoticon, then we can use a "unusual" mime type as a workaround.
