### ISSUE TITLE
请问怎么开发票

### ISSUE THREAD

**Issue by Jimyfar** [wechaty/puppet-padlocal#162]
http://pad-local.com/#/new_order
请问在这上面购买的 token 怎么开发票

微信联系不到客服，有其他方式联系到吗

**Comment by Jimyfar** [comment]
http://pad-local.com/#/new_order 
请问在这上面购买的 token 怎么开发票

**Comment by Jimyfar** [comment]
微信联系不到客服，有其他方式联系到吗

**Comment by padlocal** [comment]
客服应该已经回复您了。
