### ISSUE TITLE
【Puppet Server:DIY】ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by IanCao** [wechaty/puppet-padlocal#164]
I ran into a problem when I was running the Java starter demo.
I deploy a wechaty docker by https://wechaty.js.org/docs/puppet-services/diy and work well（Getting ip:host from chatie by token and Puppet Server port are also available）
but when i start the java client, Run failed
<img width="944" alt="image" src="https://user-images.githubusercontent.com/32847163/168426265-557b370b-b698-4515-8a0c-cfe1d542aab2.png">
This is server log in vps.

Can you give me some clues to solve it，Thanks

**Comment by padlocal** [comment]
Do you resolve this problem?

**Comment by padlocal** [comment]
Please try wechaty-puppet-padlocal@1.11.15.

If this problem still occurs, pelease reopen this issue.
