### ISSUE TITLE
启动卡死没有出现二维码，按操作步骤检查网络一切正常

### ISSUE THREAD

**Issue by jonnywang** [wechaty/puppet-padlocal#166]
启动卡死没有出现二维码，按操作步骤检查网络一切正常

20:28:36 INFO TestBot started.

**Comment by padlocal** [comment]
一般来讲，这种情况都是因为也微信服务器建立连接失败导致。网络正常，但是因为防火墙等问题仍然可能导致这个问题。

如果仍然出现这个可以把调试日志打开：`log.level("silly")`，然后再反馈详细日志信息。
