### ISSUE TITLE
如何判断自己是否在一个群里

### ISSUE THREAD

**Issue by nosun** [wechaty/puppet-padlocal#167]
由于 room.find 接口返回的 roomlist 不准确，会导致发公告失败，所以我考虑在发公告之前判断一下自己是否在群里，从而决定是否发。

有什么方法来判断自己是否在群里么？

或者有没有办法同步一下自己的群列表，从而解决自己所在的群不准确的问题。

**Comment by padlocal** [comment]
可以通过 Room 相关API进行查询：https://wechaty.js.org/docs/api/room#example-find-member-by-memberqueryfilter
