### ISSUE TITLE
接受部分特定的消息内容不全

### ISSUE THREAD

**Issue by wushuangchunjun** [wechaty/puppet-padlocal#177]
比如这句话：
@AI出单 录单
电话：15555555555
车主姓名：张建忠
身份证号：355555555555555555
身份证有效期:
2015-5-25~2025-5-25
险种：基本款 三者300万 座位3万 意外368 
业务员：林美芳-林祥根-平湖宝顺

**Comment by wushuangchunjun** [comment]
python版的和ts版本的我都试过了，都是不全

**Comment by wushuangchunjun** [comment]
@padlocal 大佬帮忙看看

**Comment by padlocal** [comment]
经过测试，消息内容本身是完整的。
<img width="1576" alt="Screen Shot 2022-07-01 at 6 29 33 PM" src="https://user-images.githubusercontent.com/64943823/176877942-9cfed90c-eb50-41b4-b07d-ebc98aad37ff.png">

只不过调用 `message.toString()` 会被截断，详情见：
https://github.com/wechaty/wechaty/blob/fd31dffaf2af0cce2d3ad7e57ae47a50e1b41aa1/src/user-modules/message.ts#L227
