### ISSUE TITLE
Waht is Padlocal Server?

### ISSUE THREAD

**Issue by ya0yy** [wechaty/puppet-padlocal#181]
i read the Design Concept, and got something. but i curious about the Padlocal Server what role has it in the process of padlocal  working. i am a java programmer, i read ts code so hard, so very very very hope tell me the answer.

**Comment by ClearLiF** [comment]
You can use express server,   i also a java programmer

**Comment by padlocal** [comment]
PadLocal server is used to encode&decode protocol related stuff, it's transparent to PadLocal end users. You don't have to care about the server details, e.g. server location, programming language.

Wechaty is the only thing you need to pay attention.
