### ISSUE TITLE
持续3天了，客服也不理我。售后逃避责任真的好吗？我刚付了一年的钱。第一天就不能用。说什么账号相关，我现在两个号随便哪个号登录都是这样。

### ISSUE THREAD

**Issue by JuoJuo** [wechaty/puppet-padlocal#239]
![image](https://user-images.githubusercontent.com/36804937/234741452-586ea2c4-3c82-4b45-b47c-0a1cb6ad2ed9.png)

**Comment by JuoJuo** [comment]
挣钱还是要凭良心吧

**Comment by JuoJuo** [comment]
售后回我了。

**Comment by blazen** [comment]
飞书回复？还是邮件？

**Comment by allforone** [comment]
> 售后回我了。

    是确认不维护了么
