### ISSUE TITLE
今天无法正常登录，扫码后会再次弹出二维码

### ISSUE THREAD

**Issue by panlina** [wechaty/puppet-padlocal#251]
RT。
启动后弹出二维码，扫了以后显示了`Confirmed(4)`以后没有正常反应（之前登录后会马上产生几条日志），过一会又打印`INFO [PuppetPadlocal] start login with type: QrLogin`并弹出了一个二维码，然后不去理它，它会定时弹出新的二维码，程序完全无法使用。
![20230604-152340](https://github.com/wechaty/puppet-padlocal/assets/18240847/5f4516de-331d-499f-9931-adb74c931b07)
我在大约1小时内测试都是这样，用的就是你们的demo。服务异常吗？

**Comment by panlina** [comment]
又过了一会再试发现恢复了。

**Comment by peefau** [comment]
亏了有7天的免费试用期，要不真不知道怎么哭
