### ISSUE TITLE
提示版本过低的我可以解决

### ISSUE THREAD

**Issue by 1376134288** [wechaty/puppet-padlocal#306]
提示版本过低的我可以解决 联系tg：@hexunfang

**Comment by 1061168609** [comment]
。。。

**Comment by huan** [comment]
Unrelated topic, and it's an im-transparent discussion, which leads to unvaluable information.

**Comment by 1061168609** [comment]
您有办法联系作者吗 @huan

**Comment by huan** [comment]
For community support, you can try the following two ways:

1. https://github.com/wechaty/puppet-supports/issues
2. https://discord.gg/7q8NBZbQzt

**Comment by dxiongya** [comment]
@huan ipadlocal服务商不提供服务，却还在收钱，你们wechaty官方确定还在官网放置他们？
