### ISSUE TITLE
[Help] transpiling myself

### ISSUE THREAD

**Issue by suntong** [wechaty/puppet-padlocal#77]
A total npm/ts newbiew question, how to transpile wechaty-puppet-padlocal myself?

I did `npm run dist`, and this is what I got comparing to what I got from `npm install`:

![image](https://user-images.githubusercontent.com/422244/118374053-0cceef00-b588-11eb-9337-2f1e833f9c45.png)

Please help. thx

**Comment by padlocal** [comment]
Why not use the package released offically?

If you have any furture questions, reopening to discucss is welcome

**Comment by suntong** [comment]
For situations just like https://github.com/padlocal/wechaty-puppet-padlocal-demo/issues/16
😢😢😢
