### ISSUE TITLE
ESM support will be required after Wechaty v0.69+

### ISSUE THREAD

**Issue by huan** [wechaty/puppet-padlocal#96]
Currently, the Wechaty ecosystem is moving from CommonJS to ES Modules.

The Wechaty will be Dual-ESM-CJS-Module supported, and the default mode will be under ESM.

- https://github.com/Chatie/tsconfig/issues/16

In order to load Wechaty Puppet under ESM mode by setting the environment variable `WECHATY_PUPPT`, or by setting the `options.puppet = 'wechaty-puppet-xxx'`, the puppet provider NPM module must support ESM.

If the puppet does not support ESM, then the Wechaty will run into the below issue: **TypeError: MyPuppet is not a constructor**

- https://github.com/wechaty/wechaty-getting-started/issues/203

Link to: https://github.com/wechaty/wechaty-puppet/issues/148

P.S. I would love to send a PR to convert padlocal to ESM, if we can have all the unit tests passed and made the GitHub Action green.

**Comment by padlocal** [comment]
I am adapting ESM for PadLocal now, feeling a little confused by following questions:

1. What are the maximum benifits of migrating to ESM for Wechaty?
2. Can we just only adopt PURE ESM while Wechaty V1.x requires Node V16+? 
3. Is DUAL model to compatible with old ecosystem code that still use `require`?

**Comment by huan** [comment]
Thanks for asking!

Here are my thoughts on those questions:

> 1. What are the maximum benifits of migrating to ESM for Wechaty?

The ESM is the next version of the Node.js ecosystem modulized system specification, it comes with lots of benefits and will eventually replace all the old ones like CJS, AMD, UMD, etc, and the community is strongly suggested to head to it as soon as possible.

For Wechaty, it can make our JS code clean and more effective, and most important, follow the latest community standard.

> 2. Can we just only adopt PURE ESM while Wechaty V1.x requires Node V16+? 

Yes, we can.

The only downside of a PURE ESM module is that it can not be used by other CJS modules anymore.

For the Wechaty community especially with the v1.x, it will be OK because Wechaty is run under ESM mode by default.

> 3. Is DUAL model to compatible with old ecosystem code that still use `require`?

Yes, the DUAL model means that when the model is running under CJS mode, it can be `required()`-ed.
